// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AIAssistant
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAIAssistantPackageString = "72094a93-38fb-4936-af38-b832374315eb";
        public static Guid guidAIAssistantPackage = new Guid(guidAIAssistantPackageString);

        public const string guidAIAssistantPackageCmdSetString = "5be5d683-76a1-4d14-b6bb-e3aff99d83a9";
        public static Guid guidAIAssistantPackageCmdSet = new Guid(guidAIAssistantPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ReviewCodeCommandId = 0x0100;
        public const int cmdidExplainCodeCommand = 0x1021;
    }
}